# ============================================
# Secret - 敏感配置
# ============================================
# 存储 Redis 密码等敏感配置
# ============================================

{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  labels:
    {{- include "server-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.secret.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
  {{ end }}
  {{ if .Values.secret.grafanaAdminUser }}
  GRAFANA_ADMIN_USER: {{ .Values.secret.grafanaAdminUser | quote }}
  {{ end }}
  {{ if .Values.secret.grafanaAdminPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secret.grafanaAdminPassword | quote }}
  {{ end }}
{{- end }}
